### ISSUE TITLE
0.0.7 getRootUrl export broken

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/nextcloud-router#12]
I'll have a closer look why next week, but it seems that the export of getRootUrl returns an object instead of a function on 0.0.7

**Comment by ChristophWurst** [comment]
I think this was caused by https://github.com/ChristophWurst/nextcloud-moment/commit/8124e2b73d0508e018c44ad1cc175d850967fbf6.

Published a new version with the correct code. Please check :)

**Comment by juliushaertl** [comment]
Thanks a lot. I'll give that a try
