### ISSUE TITLE
Allow passing args to generateXXX functions

### ISSUE THREAD

**Issue by PVince81** [nextcloud/nextcloud-router#194]
Currently only `generateUrl()` allows passing in parameters to be escaped but others like `generateOcsUrl()` doesn't.
This means that users of the latter would be tempted to do their own concatenation of args instead of using the built-in escaping.

https://github.com/nextcloud/nextcloud-router/blob/master/lib/index.ts#L53

**Comment by PVince81** [comment]
basically rewrite the other `generateXXX()` to be based on `generateUrl()` and pass in the required args

**Comment by ChristophWurst** [comment]
Sure :+1:

**Comment by blizzz** [comment]
I stumbled over a related thing. When I was using `generateUrl` today, I first  thought that the second parameter was not working. My expectation was that the function builds the query string itself, rather then replacing placeholders. Not intuitive imho.
