### ISSUE TITLE
generateOcsUrl shouldn't add a trailing '/' to the url

### ISSUE THREAD

**Issue by StCyr** [nextcloud/nextcloud-router#209]
https://github.com/nextcloud/nextcloud-router/blob/24bc4655c8f88561881970b3b419a16f388a2543/lib/index.ts#L38

None of the examples at https://docs.nextcloud.com/server/latest/developer_manual/client_apis/OCS/ocs-api-overview.html# show a trailing '/'

**Comment by ChristophWurst** [comment]
IIRC this was the case with the old ``OC.generateOcsUrl``and I just copy-pasted the code so it's a drop-in replacement

**Comment by StCyr** [comment]
So, I'll create a PR, shall I?

**Comment by ChristophWurst** [comment]
you may. I think the reason for the trailing slash was that we always added a path to the generated URL

if we drop the trailing slash then we have to release this as a new major version

cc @nextcloud/javascript

**Comment by skjnldsv** [comment]
Yes, every app will have to adapt lol

**Comment by nickvergessen** [comment]
I started work on #194 let's combine the two into a useful major, then apps can touch and improve all their calls in one go.
